#!/bin/bash
dirName=$(pwd)
srcName=$1.cpp
binName=$1.o

input=../../in.txt

cd Contest/551/
clear
if [ ! -z "$2" ]; then
	g++-5 $srcName -o $binName && ./$binName <$input
else
	g++-5 $srcName -o $binName && ./$binName
fi
echo
cd $dirName
